#include "common.h"
#define ERROR_STR_SIZE 256
#define OUTPUT_YUV420P 0
#define SFM_REFRESH_EVENT (SDL_USEREVENT + 1)
#define SFM_BREAK_EVENT (SDL_USEREVENT + 2)
#define SDL_AUDIO_BUFFER_SIZE 1024;
#define MAX_AUDIO_FRAME_SIZE 192000

